#!/usr/bin/env ruby
# chkconfig:    - 80 20

APP_NAME = 's3-virusscan'  
APP_PATH = '/opt/aws-s3-virusscan/daemon.rb'

case ARGV.first
  when 'start'
    puts "Starting #{APP_NAME}..."
    system(APP_PATH, 'start')
  when 'stop'
    system(APP_PATH, 'stop')
  when 'restart'
    system(APP_PATH, 'restart')
  when 'status'
    system(APP_PATH, 'status')
end

unless %w{start stop restart status}.include? ARGV.first
  puts "Usage: #{APP_NAME} {start|stop|restart|status}"
  exit
end
